// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel AugmentaToTexture

float Radius;

int PointsCount;

StructuredBuffer<float4> AugmentaPoints;

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void AugmentaToTexture(uint3 id : SV_DispatchThreadID)
{

    Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
}
